# Default application configuration that all configurations inherit from.

scss_files: "**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 1

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ColorKeyword:
    enabled: true

  ColorVariable:
    enabled: true

  Comment:
    enabled: true
    allowed: "^[/* ]"

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: true

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: true

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: true

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: true
    filename_extension: true

  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: hyphenated_lowercase # or 'camel_case', or 'snake_case', or a regex pattern

  NestingDepth:
    enabled: true
    max_depth: 3
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: true

  PropertyCount:
    enabled: true
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    enabled: true
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
    order: [
      animation-delay,
      animation-duration,
      animation-fill-mode,
      animation-iteration-count,
      animation-name,
      animation-play-state,
      animation-timing-function,
      animation,
      appearance,
      backface-visibility,
      background-attachment,
      background-clip,
      background-color,
      background-image,
      background-position,
      background-repeat,
      background-size,
      background,
      border-bottom-color,
      border-bottom-left-radius,
      border-bottom-right-radius,
      border-bottom-style,
      border-bottom-width,
      border-bottom,
      border-collapse,
      border-color,
      border-image,
      border-left-color,
      border-left-style,
      border-left-width,
      border-left,
      border,
      border-radius-bottomleft,
      border-radius-bottomright,
      border-radius-topleft,
      border-radius-topright,
      border-radius,
      border-right-color,
      border-right-style,
      border-right-width,
      border-right,
      border-spacing,
      border-style,
      border-top-color,
      border-top-left-radius,
      border-top-right-radius,
      border-top-style,
      border-top-width,
      border-top,
      border-width,
      bottom,
      box-align,
      box-flex,
      box-orient,
      box-pack,
      box-shadow,
      box-sizing,
      clear,
      clip,
      color,
      content,
      cursor,
      direction,
      display,
      filter,
      float,
      font-family,
      font-size,
      font-smoothing,
      font-style,
      font-weight,
      font,
      height,
      hyphens,
      interpolation-mode,
      left,
      letter-spacing,
      line-height,
      list-style-image,
      list-style-position,
      list-style-type,
      list-style,
      margin-bottom-collapse,
      margin-bottom,
      margin-collapse,
      margin-left-collapse,
      margin-left,
      margin-right-collapse,
      margin-right,
      margin-top-collapse,
      margin-top,
      margin,
      marks,
      max-height,
      max-width,
      min-height,
      min-width,
      opacity,
      osx-font-smoothing,
      outline-offset,
      outline,
      overflow-x,
      overflow-y,
      overflow,
      padding-bottom,
      padding-left,
      padding-right,
      padding-top,
      padding,
      page,
      pointer-events,
      position,
      quotes,
      resize,
      right,
      set-link-source,
      size,
      speak,
      src,
      table-layout,
      text-align,
      text-decoration,
      text-indent,
      text-overflow,
      text-rendering,
      text-shadow,
      text-size-adjust,
      text-transform,
      top,
      transform,
      transition-delay,
      transition-duration,
      transition-property,
      transition-timing-function,
      transition,
      unicode-bidi,
      user-select,
      vertical-align,
      visibility,
      white-space,
      width,
      word-break,
      word-spacing,
      word-wrap,
      z-index,
      zoom
  ]

  PropertySpelling:
    enabled: true
    extra_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: false
    allow_element_with_id: false

  PseudoElement:
    enabled: true

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM #hyphenated_lowercase # or 'strict_BEM', or 'hyphenated_BEM', or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3, 4]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space'

  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    enabled: true
    style: one_space # or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
